add colors to the output

diff --git a/bin/stub-check b/bin/stub-check
--- a/bin/stub-check
+++ b/bin/stub-check
@@ -1,15 +1,20 @@
 #!/usr/bin/env bash
 
-# convenience to pretend like this is perl
-die () {
-    # the unicode value prints '✗'
-    printf '\u2717 %s\n' "${1:-'something has gone horribly wrong'}"
-    exit 1
+# handle colors and the unicode symbols '✓' and '✗'
+readonly NORMAL="$(tput sgr0)"
+readonly RED_FAIL="$(tput setaf 1)$(printf '\u2717')"
+readonly GREEN_PASS="$(tput setaf 2)$(printf '\u2713')"
+
+# format the success messages
+success () {
+    printf '%s\n' "${GREEN_PASS}${NORMAL} ${1}"
 }
 
-success () {
-    # the unicode value prints '✓'
-    printf '\u2713 %s\n' "$1"
+# convenience to pretend like this is perl
+die () {
+    local err="${1:-something has gone horribly wrong}"
+    printf '%s\n' "${RED_FAIL}${NORMAL} ${err}"
+    exit 1
 }
 
 # make sure we are in the right place
