Minor nitpicks
- Remove unnecessary semicolons
- Match style of `for ...; do` in `if ...; then`
- Use more portable shebang (out of habit, if nothing else)

diff --git a/bin/test-examples b/bin/test-examples
--- a/bin/test-examples
+++ b/bin/test-examples
@@ -1,27 +1,27 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
-if [[ ! -d "exercises" ]]
-then
-    {echo "exercises directory not found!"; exit 1}
+if [[ ! -d "exercises" ]]; then
+    echo "exercises directory not found!"
+    exit 1
 fi
 
 cd ./exercises
 
 for ex in *; do
-    err_cnt=0;
-    impl="${ex}.el";
-    cd $ex;
-    mv $impl "${impl}.tmp";
-    cp example.el $impl;
-    emacs -batch -l ert -l "${ex}-test.el" -f ert-run-tests-batch-and-exit;
-    let "err_cnt += $?";
-    mv "${impl}.tmp" $impl;
-    cd -;
+    err_cnt=0
+    impl="${ex}.el"
+    cd $ex
+    mv $impl "${impl}.tmp"
+    cp example.el $impl
+    emacs -batch -l ert -l "${ex}-test.el" -f ert-run-tests-batch-and-exit
+    let "err_cnt += $?"
+    mv "${impl}.tmp" $impl
+    cd -
 done
 
 if [ $err_cnt -ne 0 ]
 then
-    exit 1;
+    exit 1
 else
-    exit 0;
+    exit 0
 fi
